Add a statistic endpoint
Gamify-IT/finitequiz-backend pull request #16
Opened 2023-01-07 17:54 UTC by maexled

Closes Gamify-IT/issues#379

2023-01-10 21:45 UTC, Aaron2000119 requested changes

2023-01-10 21:45 UTC, Aaron2000119 commented on src/main/java/de/unistuttgart/finitequizbackend/service/StatisticService.java
> +        // TODO: make this work that every timedistrubution has the correct amount of counts
```suggestion
```
remove todo

2023-01-10 21:45 UTC, Aaron2000119 commented on src/main/java/de/unistuttgart/finitequizbackend/service/StatisticService.java
> +    public List<TimeSpentDistribution> getTimeSpentDistributions(final UUID configurationId) {
method probably to long

2023-01-11 14:20 UTC, Gr33ndev approved these changes

2023-01-19 14:18 UTC, merged